version: '3.8'

services:
  graph:
    container_name: graph_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes: [".:/graphApp'", "/graphApp/node_modules"]
    ports: ["8080:8080"]